### ISSUE TITLE
encoding of 4000+ Character data

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jordao76/nbarcodes#5]
```
Hi,
I want to encode 4000+ character data in bar code.
I have tried with your dll. but application is going in hanging state.

Do you have any idea for it.



```

Original issue reported on code.google.com by `amolpati...@gmail.com` on 31 May 2014 at 1:51

**Comment by jordao76** [comment]
Closing as resolved. If the issue persists, or if there's more info about it, please open another issue.
