### ISSUE TITLE
DPI setting and Parameter is not valid

### ISSUE THREAD

**Issue by okcken** [jordao76/nbarcodes#7]
Hi,

If we set the DPI to 300, the barcode has a black box on it. Please see attachment...
![nbarcode-dpi-issue](https://cloud.githubusercontent.com/assets/17534909/13382598/1b4abf9a-de3e-11e5-86d9-3b9d725f25f2.png)
However, if we set the DPI to 200, it is fine. It does the same thing around 250 as well...

A second issue is if we try multi-page barcode, it give s a "Parameter is not valid" error. 
![nbarcode-parameter is not valid](https://cloud.githubusercontent.com/assets/17534909/13382615/8f1e2d58-de3e-11e5-8c64-73fae207f79e.PNG)

However, these two issues are not happening if the DPI is set to 200.

Thanks,

**Comment by jordao76** [comment]
Can you please share the code you're using to generate that barcode? I've generated a 300 DPI Code 128 barcode with the same text, and saved it to a file, without a problem. Also, what do you mean as multi-page barcode?

**Comment by okcken** [comment]
Sure. I have attached the code for your review. As I said, both of these codes work if the DPI is set to 200 or lower.
[Barcodeissue.pdf](https://github.com/jordao76/nbarcodes/files/151182/Barcodeissue.pdf)

**Comment by jordao76** [comment]
I noticed you're using some old values for the NarrowWidth and the WideWidth, maybe you're using NBarCodes version 2? In version 3, those values are in inches, and the ones you're using won't work with 300 DPI. You can try using NBarCodes version 3 (get the latest from Nuget) with the default values for NarrowWidth and WideWidth. Also, what are the types of rectText and gfx? I assume gfx is a Graphics object, but where is it derived from?

**Comment by jordao76** [comment]
Closing as resolved. If the problem persists, please open another issue.
